### ISSUE TITLE
Unsatisfied APIs detected

### ISSUE THREAD

**Issue by Insane-neal** [Decawave/mynewt-dw1000-apps#30]
Hi, all

I'm trying to build dwm1001_listener application on MacOS. Mynewt version is 1.5. It gave the error:
`Error: Unsatisfied APIs detected:
    * UWB_CIR_HW_IMPL, required by: lib/cir`
What shall I do to fix this issue?

**Comment by horst-m** [comment]
I'm having the same issue here on Linux.
suggestions welcome

**Comment by leobotler** [comment]
I had the same issue and solved by adding the following lines in the pkg.yml of the listener:

pkg.apis:
    - UWB_CIR_HW_IMPL

**Comment by Beetix** [comment]
I also stumbled upon the same error.

I think this issue should be reopened since @leobotler solution is a workaround not a fix.

`UWB_CIR_HW_IMPL` should only be defined by packages providing a CIR hardware layer implementation as in the [cir_dw1000 package](https://github.com/Decawave/mynewt-dw1000-core/blob/d6b1414f1b4527abda7521a304baa1c648244108/lib/cir/cir_dw1000/pkg.yml#L30).

Looking at [uwb_dw1000 package](https://github.com/Decawave/mynewt-dw1000-core/blob/d6b1414f1b4527abda7521a304baa1c648244108/hw/drivers/uwb/uwb_dw1000/pkg.yml#L33) we can understand why the implementation is missing. `CIR_ENABLED` being set to `0` means that `cir_dw1000` is not included.

Following this logic, [listener package CIR dependency](https://github.com/Decawave/mynewt-dw1000-apps/blob/b2768e3b18417849be385bb1d422a3eb8c58cc61/apps/listener/pkg.yml#L38) could be changed to:
```
pkg.deps.CIR_ENABLED:
    - "@mynewt-dw1000-core/lib/cir"
```
Doing so still does not compile due to a missing CIR define [used here](https://github.com/Decawave/mynewt-dw1000-apps/blob/b2768e3b18417849be385bb1d422a3eb8c58cc61/apps/listener/src/main.c#L121). A simple fix is to wrap the block with a `#if MYNEWT_VAL(CIR_ENABLED)`. A more comprehensive fix seems be to wrapping (in the same manner) all the code concerning `acc_samples_to_load` config parameter since it only makes sense when CIR is enabled.
